In [10]:
import pandas as pd

In [11]:
df = pd.read_csv('results.csv')
df = df.sort_values(['tempo de execução'], ignore_index=True)
df

,instância,número de cidades,tempo de execução,custo da solução (VND),distância utilizada
0,att48,48,0.03,10782,pseudo-euclidiana
1,berlin52,52,0.11,8043,euclidiana 2D
2,pr76,76,0.21,121128,euclidiana 2D
3,st70,70,0.22,709,euclidiana 2D
4,kroB100,100,0.27,25393,euclidiana 2D
5,kroD100,100,0.28,24721,euclidiana 2D
6,rat99,99,0.44,1399,euclidiana 2D
7,kroE100,100,0.45,24268,euclidiana 2D
8,kroC100,100,0.47,22968,euclidiana 2D
9,kroA100,100,0.50,22489,euclidiana 2D
10,lin105,105,0.51,18230,euclidiana 2D
11,pr144,144,0.54,61400,euclidiana 2D
12,pr136,136,0.57,110103,euclidiana 2D
13,pr152,152,0.77,79996,euclidiana 2D
14,pr107,107,0.86,44921,euclidiana 2D
15,pr124,124,0.87,61823,euclidiana 2D
16,kroA150,150,0.99,28612,euclidiana 2D
17,kroB200,200,2.27,33375,euclidiana 2D
18,kroB150,150,2.65,27442,euclidiana 2D
19,rat195,195,2.81,2493,euclidiana 2D
20,kroA200,200,3.78,31518,euclidiana 2D